
- name: pull base image
  docker_image:
    name:        "{{ item.value.name }}"
    tag:         "{{ item.value.version }}"
    docker_host: "{{ item.value.docker_host  | default('unix://var/run/docker.sock')}}"
    state:       present
  with_dict:  "{{ docker_builder.pull.base_images  }}"
